## Use an official OpenJDK runtime as a parent image
#FROM openjdk:11-jre
#  # Set the working directory to /app
#WORKDIR /app
#
#  # Copy the current directory contents into the container at /app
#COPY ./target/LoginService-0.0.1-SNAPSHOT.jar /app/LoginService-0.0.1-SNAPSHOT.jar
#
#  # Expose the port the app runs on
#EXPOSE 8080
#
#  # Specify the command to run on container start
#CMD ["java", "-jar", "LoginService-0.0.1-SNAPSHOT.jar"]


FROM openjdk:11-jdk-alpine
MAINTAINER .com
COPY target/docker-LoginService-0.0.1-SNAPSHOT.jar LoginService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","LoginService-0.0.1-SNAPSHOT.jar"]