#server:
#  port: 9002
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://43.205.24.208:5432/login_system
#    username: postgres
#    password: pgadmin
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  application:
#    name: USER-SERVICE
#  main:
#    allow-circular-references: true
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#
#app:
#  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
#  jwt-expiration-milliseconds: 604800000
